small fix for bound cutoff
uwblueprint/shoe-project pull request #192
Opened 2021-01-23 18:28 UTC by hanlinc27

2021-01-23 18:29 UTC, DinuWije approved these changes

2021-01-23 18:39 UTC, AbhiPrasad requested changes

2021-01-23 18:39 UTC, AbhiPrasad commented on ui/src/pages/ShoeMap.tsx
> +  mapBounds = L.latLngBounds(southWest, northEast);
let's make sure these are declared as `const`

2021-01-24 01:00 UTC, AbhiPrasad commented on ui/src/pages/ShoeMap.tsx
> +    mapBounds = L.latLngBounds(southWest, northEast);
I would declaring them individually for +readability
```suggestion
  const southWest = L.latLng(40.712, -50.227);
  const northEast = L.latLng(70.774, -150.125);
  const mapBounds = L.latLngBounds(southWest, northEast);
```

2021-01-24 01:00 UTC, AbhiPrasad approved these changes

2021-01-25 02:27 UTC, merged