Help Panel, Story Drawer, Welcome Tutorial mobile responsiveness
uwblueprint/shoe-project pull request #196
Opened 2021-01-24 02:53 UTC by hanlinc27

Mobile adjustments for different components (font-size, component size) 
### Help Panel
![Screen Shot 2021-01-23 at 7 28 44 PM](https://user-images.githubusercontent.com/19617248/105619833-756d4280-5dc4-11eb-88d1-a0ef58a4093c.png)
### Story Drawer
![Screen Shot 2021-01-23 at 7 41 29 PM](https://user-images.githubusercontent.com/19617248/105619834-769e6f80-5dc4-11eb-8790-28fadff4366c.png)
### Welcome Tutorial
![Screen Shot 2021-01-23 at 8 07 27 PM](https://user-images.githubusercontent.com/19617248/105619847-a3528700-5dc4-11eb-910b-8295b98e65fd.png)
![Screen Shot 2021-01-23 at 8 18 46 PM](https://user-images.githubusercontent.com/19617248/105619849-a3eb1d80-5dc4-11eb-8d89-7a3e07b1f6a4.png)

Todo: Filter and Control (Dinu), Preview (Jeffrey)

2021-01-25 02:24 UTC, DinuWije approved these changes

2021-01-26 23:51 UTC, AbhiPrasad requested changes

2021-01-26 23:51 UTC, AbhiPrasad commented on ui/src/pages/ShoeMap.tsx
> +<<<<<<< HEAD
Make sure we take care of these

2021-01-27 01:05 UTC, hanlinc27 commented on ui/src/pages/ShoeMap.tsx
> +<<<<<<< HEAD
oops my bad will rebase

2021-01-27 02:53 UTC, AbhiPrasad approved these changes

2021-01-27 03:13 UTC, merged