[WIP] Login page
uwblueprint/shoe-project pull request #223
Opened 2021-02-10 03:18 UTC by DinuWije

## Functionality:
Currently logs a message to console and redirects the user to /admin endpoint when Google Sign In button is clicked

## Todo:
- Add API call to backend to log the user in when the button is clicked
- Edit CSS once the Figma designs are hi-fi
## /login endpoint: 
![image](https://user-images.githubusercontent.com/50289930/107459526-65739380-6b24-11eb-8a9e-c507cd8237b3.png)

## /unauthorized endpoint:
![image](https://user-images.githubusercontent.com/50289930/107459505-568ce100-6b24-11eb-82e3-40a2dcbb2849.png)

2021-02-10 03:50 UTC, AbhiPrasad approved these changes
sick, good stuff.

Plz run `yarn fix` before merge!

2021-02-10 05:39 UTC, hanlinc27 requested changes

2021-02-10 05:39 UTC, hanlinc27 commented on ui/src/pages/Login.tsx
> +  font-size: 20px;
can you move the TitleText and Message Text to the typography file? And then use fontSize.whicheverText for consistency.

2021-02-10 05:39 UTC, hanlinc27 commented on ui/src/pages/Login.tsx
> +  font-size: 20px;
Wait nvm I realized this is all lofi so the font sizes are still in the air - would be good though to still keep the message and title texts in the typography file like the other components :)

2021-02-10 05:39 UTC, hanlinc27 commented on ui/src/pages/Login.tsx
>  import { Redirect } from "react-router-dom";
run `yarn run fix`

2021-02-10 05:39 UTC, hanlinc27 commented on ui/src/App.tsx
> +              <Login login={true} />
it will have a value of **true** by default so you can just put **login** instead of explicitly defining

2021-02-17 01:42 UTC, AbhiPrasad commented on ui/src/pages/Login.tsx
> +export const Login: React.FC<LoginProps> = (props) => {
let's just destructure the props here

2021-02-17 04:32 UTC, hanlinc27 approved these changes

2021-02-17 18:38 UTC, merged