Jeffrey/pin-preview
uwblueprint/shoe-project pull request #234
Opened 2021-02-20 21:14 UTC by liu-jeffrey

Modify pin preview to be mobile compatible. Changes include:

- Modifying the CSS sizing of the popup's image, description and buttons
- Changes to leaflet's default styling on popups (eg close-button size, pop-up drop shadows)
- Fade-out line clamping 
- Positioning of the popup to be above the pin instead of to the left

God save CSS.

2021-02-20 21:25 UTC, hanlinc27 requested changes
nice! 😄 thanks for taking on this ticket

2021-02-20 21:25 UTC, hanlinc27 commented on ui/src/components/PinPreview.tsx
> +      {/* <> */}
remove comment
```suggestion
```

2021-02-20 21:25 UTC, hanlinc27 commented on ui/src/components/PinPreview.tsx
> +    // </>
same as above
```suggestion
```

2021-02-20 21:25 UTC, hanlinc27 commented on ui/src/components/Pin.tsx
> +    width: fit-content !important;
Did you test without `!important` for any of these declarations? Do they all require it?

2021-02-20 21:31 UTC, AbhiPrasad reviewed
css got me pogged up

2021-02-20 21:31 UTC, AbhiPrasad commented on ui/src/components/PinPreview.tsx
> +    {/* <> */}
```suggestion
```

2021-02-20 21:31 UTC, AbhiPrasad commented on ui/src/components/PinPreview.tsx
> +    // </>
```suggestion
```

2021-02-20 21:31 UTC, AbhiPrasad commented on ui/src/components/Pin.tsx
> +  const rightPaddingPoint =
Hmm we might have to put this in a https://reactjs.org/docs/hooks-reference.html#uselayouteffect hook. (also will address on window resize) So something like:

```ts
// outside of component
const LEFT_PADDING_POINT = L.point(500, 75);
const RIGHT_PADDING_POINT = L.point(100, 400);

type PaddingState =
  | { left: L.Point; right: L.Point }
  | { left: null; right: null };

// inside component
const [paddingPoints, setPaddingPoints] = React.useState<PaddingState>({
  left: LEFT_PADDING_POINT,
  right: RIGHT_PADDING_POINT,
});

React.useLayoutEffect(() => {
  function updateSize() {
    if (window.screen.height <= parseInt(device.mobile)) {
      setPaddingPoints({left: null, right: null});
    } else {
      setPaddingPoints({left: LEFT_PADDING_POINT, right: RIGHT_PADDING_POINT});
    }
  }
  window.addEventListener("resize", updateSize);
  updateSize();
  return () => window.removeEventListener("resize", updateSize);
});

// return
<StyledPopup
  autoPanPaddingTopLeft={paddingPoints.left}
  autoPanPaddingBottomRight={paddingPoints.right}
>
```

I wrote this whole thing in GitHub, so there is probably syntax errors and other stuff, but hopefully this gives you a good direction

2021-02-20 21:32 UTC, AbhiPrasad commented on ui/src/components/Pin.tsx
> +  const rightPaddingPoint =
actually we might have to compute this outside of the Pin so that we dont add an event listener for each pin

2021-02-27 23:32 UTC, hanlinc27 requested changes
I'm not sure if this is finished, but there's some merge conflicts that need to be cleaned up.

2021-02-27 23:32 UTC, hanlinc27 commented on ui/src/components/Pin.tsx
> +<<<<<<< HEAD
```suggestion
```
delete merge conflict

2021-02-27 23:32 UTC, hanlinc27 commented on ui/src/components/Pin.tsx
> +>>>>>>> 79f636f8b2d70be5a17d7ba99a90335ac2442ad0
```suggestion
```

2021-02-27 23:32 UTC, hanlinc27 commented on ui/src/components/PinPreview.tsx
> +>>>>>>> 79f636f8b2d70be5a17d7ba99a90335ac2442ad0
```suggestion
```

2021-02-27 23:32 UTC, hanlinc27 commented on ui/src/components/PinPreview.tsx
> +<<<<<<< HEAD
```suggestion
```

2021-02-28 15:29 UTC, hanlinc27 approved these changes

2021-02-28 16:57 UTC, AbhiPrasad approved these changes

2021-03-03 00:58 UTC, merged