use postal code stuff in sseding
uwblueprint/shoe-project pull request #275
Opened 2021-03-27 19:55 UTC by m-penny

2021-03-31 00:15 UTC, nimwijetunga requested changes
Mostly just testing

2021-03-31 00:15 UTC, nimwijetunga commented on internal/database/migrations/migrations.go
> +	for index, story := range stories {
Can you run `make seed` and make sure this works and is seeded properly

2021-03-31 00:15 UTC, nimwijetunga commented on internal/location/coordinates.go
> +	resp, err := http.Get(fmt.Sprintf(zipCodeURL, finder.zipCodeToken, city, limit+2))
Did you test that this now works?

2021-04-03 18:12 UTC, m-penny commented on internal/database/migrations/migrations.go
> +	for index, story := range stories {
yeah i ran it and it worked

2021-04-03 18:12 UTC, m-penny commented on internal/location/coordinates.go
> +	resp, err := http.Get(fmt.Sprintf(zipCodeURL, finder.zipCodeToken, city, limit+2))
yeah, tested

2021-04-03 18:50 UTC, nimwijetunga approved these changes
LGTM

2021-04-03 18:52 UTC, merged