[WIP] Set up FE testing
uwblueprint/shoe-project pull request #50
Opened 2020-10-14 23:50 UTC by lesliexin

Added react testing and jest to the project. 

To do:
- Imports are throwing errors

2020-10-15 01:08 UTC, AbhiPrasad requested changes
We'll have to adjust the prettier and eslint linting to apply to the `__test__` directory as well, you can do this by adjusting the yarn scripts to (apply to everywhere that uses `src/`):

```diff
-"lint:prettier": "prettier --check src/",
+"lint:prettier": "prettier --check {src,__tests__}/",
```

2020-10-15 02:05 UTC, hanlinc27 requested changes
Also for eslint?

2020-10-15 02:05 UTC, hanlinc27 commented on ui/package.json
>      "lint:eslint": "eslint src/ --cache --format stylish",
Also include for eslint?

2020-10-18 16:56 UTC, hanlinc27 approved these changes

2020-10-18 17:12 UTC, AbhiPrasad approved these changes

2020-10-18 17:49 UTC, merged